-- Sequences
CREATE SEQUENCE IF NOT EXISTS users_id_seq;

-- Table Definition
CREATE TABLE users (
    "id" int8 NOT NULL DEFAULT nextval('users_id_seq'::regclass),
    "first_name" varchar NOT NULL,
    "email" varchar NOT NULL,
    "email_verified_at" timestamptz,
    "password" varchar NOT NULL,
    "expiry_date" timestamptz,
    "credit" float8 NOT NULL DEFAULT '0'::double precision,
    "company_name" varchar NOT NULL,
    "attachment_url" varchar,
    "birth_day" timestamptz,
    "mobile_number" varchar NOT NULL,
    "approved" bool NOT NULL DEFAULT false,
    "bank_is_activated" bool NOT NULL DEFAULT false,
    "beneficiary_name" varchar,
    "beneficiary_address_building_no" varchar,
    "beneficiary_address_street_name" varchar,
    "beneficiary_address_neighborhood" varchar,
    "beneficiary_address_city" varchar,
    "bank_name" varchar,
    "account_number" varchar,
    "iban" varchar,
    "is_admin" bool,
    "plan_id" int8,
    "remember_token" varchar,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    "last_name" varchar NOT NULL,
    "last_subscription_date" timestamptz,
    "last_subscription_fees" float8,
    "phone_valid" bool NOT NULL DEFAULT false,
    "avg_of_monthly_shipments" int8,
    "shipment_weights_min" float8,
    "shipment_weights_max" float8,
    "store_url" varchar,
    "phone_verified" bool NOT NULL DEFAULT false,
    "monthly_duration_start" timestamptz,
    "monthly_duration_end" timestamptz,
    "phone_last_update" date,
    "active" bool NOT NULL DEFAULT true,
    "role_id" int8,
    "affiliation_code" varchar NOT NULL,
    "affiliation_active" bool NOT NULL DEFAULT false,
    "affiliator_id" int8,
    "deleted_at" timestamptz,
    "auto_created" bool NOT NULL DEFAULT false,
    "info_completed" bool NOT NULL DEFAULT true,
    "post_paid" bool NOT NULL DEFAULT false,
    "after_dlv_cod_diff" bool NOT NULL DEFAULT false,
    "send_wa_msg_for_returns" bool NOT NULL DEFAULT false,
    "test_mode" bool NOT NULL DEFAULT false,
    "account_id" int8,
    "bonus_credit_on_charge" bool NOT NULL DEFAULT false,
    "thirdmile_agent" bool NOT NULL DEFAULT false,
    PRIMARY KEY ("id")
);